export const CONVERSATIONS  = [
  {
    id: "c1",
    name: "Shreyance Bodh",
    otherUserId: "u1",
    updatedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    lastMessage: { text: "Let's finalize the screens today." },
    unreadCount: 2,
  },
  {
    id: "c2",
    name: "Rahul Verma",
    otherUserId: "u2",
    updatedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    lastMessage: { text: "Pushed fixes to the branch." },
    unreadCount: 0,
  },
  {
    id: "c3",
    name: "Abhishek Yadav",
    otherUserId: "u3",
    updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    lastMessage: { text: "Sync at 5 PM?" },
    unreadCount: 0,
  },
  {
    id: "c4",
    name: "Neha Sharma",
    otherUserId: "u4",
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    lastMessage: { text: "Can you review my PR?" },
    unreadCount: 1,
  },
  {
    id: "c5",
    name: "Vikram Singh",
    otherUserId: "u5",
    updatedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    lastMessage: { text: "Deployment was successful." },
    unreadCount: 0,
  },
  {
    id: "c6",
    name: "Priya Mehta",
    otherUserId: "u6",
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    lastMessage: { text: "On my way to the meeting." },
    unreadCount: 3,
  },
  {
    id: "c7",
    name: "Arjun Gupta",
    otherUserId: "u7",
    updatedAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    lastMessage: { text: "Let's pair program tomorrow." },
    unreadCount: 0,
  },
  {
    id: "c8",
    name: "Sneha Rathi",
    otherUserId: "u8",
    updatedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    lastMessage: { text: "Don’t forget the client call." },
    unreadCount: 1,
  },
  {
    id: "c9",
    name: "Karan Malhotra",
    otherUserId: "u9",
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    lastMessage: { text: "Shared the docs on drive." },
    unreadCount: 0,
  },
  {
    id: "c10",
    name: "Simran Kaur",
    otherUserId: "u10",
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    lastMessage: { text: "See you at the standup." },
    unreadCount: 4,
  },
];